signature:
  secretGroup:
    - code: TEST_CODE1
      accessKey:
        test-key1: L5nqjXlcziKIDa6b
        test-key2: mSlUAzz5ff9ViP2H
    - code: TEST_CODE2
      accessKey:
        testKeyId21: testKeySecret21
        testKeyId22: testKeySecret22
spring:
  redis:
    host: 192.168.56.102
    port: 6379
    lettuce:
      shutdown-timeout: 0
    database: 0
